### ISSUE TITLE
Trial Branch

### ISSUE THREAD

**Issue by JeanHuit** [JeanHuit/finance#1]
There's an issue implementing SugarOrm in the register class. @jeffgodwyll Kindly look at it for me. 

idea: want to register a new user to a local db. {username/pincode}
if you look at the other branches, i implemented with sharedpref which isn't good

**Comment by jeffgodwyll** [comment]
OK. Just seeing this. Lemme pull and build and see

**Comment by jeffgodwyll** [comment]
e69810939688f87dbca63c2a117fd5b11f6e8791

**Comment by JeanHuit** [comment]
The issue still remains.  Even after deleting and pulling repo once more

**Comment by JeanHuit** [comment]
Still the same issue:
We would work on the master branch, as it's at par with the trial. Or create another branch if you want to implement something.
I have seen some changes in the displaylogin class.
but the initial page is the register class. this then skips to the displaylogin after the first time registration. I removed the code to bypass register.

> 
Thats the error I am receiving.

> 07-31 00:05:50.656 7399-7399/nibbleitconsult.com.finances E/SQLiteLog: (1) no such table: USER
07-31 00:05:50.656 7399-7399/nibbleitconsult.com.finances D/AndroidRuntime: Shutting down VM
07-31 00:05:50.657 7399-7399/nibbleitconsult.com.finances E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: nibbleitconsult.com.finances, PID: 7399
                                                                            java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
                                                                                at android.view.View.performClick(View.java:5198)
                                                                                at android.view.View$PerformClick.run(View.java:21147)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                                at android.view.View.performClick(View.java:5198) 
                                                                                at android.view.View$PerformClick.run(View.java:21147) 
                                                                                at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                             Caused by: android.database.sqlite.SQLiteException: no such table: USER (code 1): , while compiling: INSERT OR REPLACE  INTO USER(PINCODE,ID,NAME) VALUES (?,?,?)
                                                                                at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                                at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                                at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                                at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
                                                                                at com.orm.SugarRecord.save(SugarRecord.java:266)
                                                                                at com.orm.SugarRecord.save(SugarRecord.java:360)
                                                                                at nibbleitconsult.com.finances.Register.setPinCode(Register.java:40)
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                                                                                at android.view.View.performClick(View.java:5198) 
                                                                                at android.view.View$PerformClick.run(View.java:21147) 
                                                                                at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
07-31 00:07:52.274 7399-7399/nibbleitconsult.com.finances I/Process: Sending signal. PID: 7399 SIG: 9

**Comment by jeffgodwyll** [comment]
I think you need to scrub your phone :laughing: 

Anyway I sometimes have issues with android studio. What I do:

 1. Clean project, rebuild ...
 2. Invalidate cache and restart...
 3. Disable instant run(since android studio 2+)

**Comment by JeanHuit** [comment]
Its event the emulator , not my phone itself.

**Comment by jeffgodwyll** [comment]
Ebei! lol

**Comment by JeanHuit** [comment]
I just decided to kill this issue and the project itself. 
came across gnu cash. 
why reinvent the wheel :)

**Comment by jeffgodwyll** [comment]
Cool. Your call :smile:
